### ISSUE TITLE
TGT backend supported?

### ISSUE THREAD

**Issue by josdotso** [rancher/longhorn#112]
I may be completely off in my assessment of the issue I'm facing. However, trying to run longhorn inside https://github.com/kubernetes-sigs/kubeadm-dind-cluster doesn't seem to be working out because longhorn can't reach the open-iscsi service (iscsi). Even when open-iscsi is installed in the containerized k8s nodes (where systemd is I believe supported), starting the iscsid service fails its own health check.

I believe this is because iscsid won't work in containers which are not `--net=host` and also will not work without the kernel modules necessary for iscsid to function.  I'm on Docker for Mac.  I `screen` attached to the xhyve VM running docker and lsmod reports the iscsi modules are loaded.  Somewhere in a Google Groups post, I found a person saying iscsi doesn't work without host networking.  I'm not clear on why exactly.

Anywho -- I'm trying now to bring up tgt instead of open-iscsi inside these containers.  First run without deep debugging seems to fail in a similar way as before.  My theory is that Longhorn expects iscsid not tgt in the backend, so what I'm trying may not work at all.

Can you confirm if tgt works at the bottommost layer?  Any tips on getting longhorn running in kube-dind-cluster?

Thanks!

refs:
- https://github.com/kubernetes-sigs/kubeadm-dind-cluster/issues/164
- https://github.com/kubernetes-sigs/kubeadm-dind-cluster/issues/156

**Comment by josdotso** [comment]
ref: https://groups.google.com/forum/#!topic/open-iscsi/xBwQGhThNso

**Comment by yasker** [comment]
I don't know about the kube-dind-cluster. But you're right. You need at least got `open-iscsi` running on the host before you can run Longhorn. There isn't much we can do if `iscsid` cannot start.

`iscsid` doesn't work without `--net host` is because iscsid is communicating with iscsiadm using netlink protocol, which doesn't support namespace. That's the exactly reason we don't package the iscsiadm/iscsid inside the Longhorn container, instead we require that it must be available on the host.

Longhorn itself is using tgt as the iscsi target. You need a iscsi initiator to connect to it. I think the only widely used iscsi initiator out there is open-iscsi.

If you're able to get `open-iscsi` works on your cluster, but still cannot get Longhorn working, we have a new build should make it work. But `open-iscsi` is indeed required.

**Comment by josdotso** [comment]
I can only hope iscsi gains namespace support soon.

I can imagine a scheme that would in theory work for kubeadm-dind-cluster, but I don't know exactly how to implement it.  If the 1 master node of the cluster ran `--network=host`,  master and nodes ran mounting the host's docker socket, and longhorn were in installed such that replicas=1 and schedule to the master node, I bet this would work.  But I don't have the cycles to implement that at the moment, and I bet it wouldn't be accepted upstream -- since host networking is not good in most cases.

Thanks!  Will close this now.

**Comment by josdotso** [comment]
Actually, last thought: If Longhorn had an option to schedule the iscsid in a daemonset instead of assuming it runs natively on the host, we'd be golden by mounting the host's docker socket and scheduling iscsid pods w/host networking.  FEATURE REQUEST  :-)

**Comment by yasker** [comment]
Does kubeadm-dind-cluster support iscsi volume? iscsi is one of volume interface that supported natively by Kubernetes. See https://kubernetes.io/docs/concepts/storage/volumes/

If it isn't supported by kubeadm-dind-cluster, I think it's valid to say that it should be fixed by them.

To me, it feels like beyond Longhorn's scope to deploy the open-iscsi, since it will impact the existing host environment. Well, at least for now.

**Comment by jellonek** [comment]
@yasker what do you mean by `using netlink protocol, which doesn't support namespace`? Which namespace? All network configuration things relay on netlink protocol and are working perfectly in different namespaces (sometimes only requiring remounting `/sys` for particular thread to refresh a view for content in `/sys/class/net` - maybe it's also needed for iscsiadm to access `/sys/devices/platform` in a shape for a different ns?).

**Comment by yasker** [comment]
@jellonek Thanks for the clarify. I meant for the netlink used by kernel iSCSI part. I didn't dig deep into it, but it seems doesn't support namespace isolation in the iSCSI case. E.g. https://groups.google.com/forum/#!topic/open-iscsi/xBwQGhThNso .

So the result is we cannot run multiple open-iscsi instances on one host since it will require `--net host` to be started inside the container.

If we can get multiple open-iscsi instances running inside container, it will be great. I will give `/sys` a try to see if it helps.

**Comment by jellonek** [comment]
If that is not supported by kernel iscsi module - we will be out of luck. It's exactly as Chris describes in linked thread, namespace filtering works for `/sys/class`. So the main limitation is on kernel iscsi module which does not have a support for multiple ipc sockets, so there is no possibility to have in parallel multiple instances of iscsid on the same host, so that means that kubeadm-dind-cluster which tries to mimic multinode setup using "containers as a nodes" approach could work with current version of iscsid only in single worker node setup.

**Comment by yasker** [comment]
I ses. That should be the reason that kubeadm-dind-cluster doesn't support iscsi (I assume).
