### ISSUE TITLE
Can not delete volume after create volume in volume page

### ISSUE THREAD

**Issue by ly5156** [rancher/longhorn#121]
1. The volume data by websocket pushed miss self property in links object after create volume 
2. EngineImage page and node page have the similar situation.
3. Delete multiple disks at the same time, the data which the websocket last pushed miss data property

**Comment by yasker** [comment]
I think the third item is different from the first two. Rancher API suppose to fill those fields. The third item is because Rancher API Library uses `omitempty` for the `data` field. So the frontend needs to deal with it.

@LLParse can you take a look at first two items?

**Comment by TehTotalPwnage** [comment]
Looks like it's not just after volume creation. When deleting one volume successfully but then deleting another volume, that volume won't delete either. Upon closer inspection, the issue looks like one with the WebSocket connection in general: all WebSocket events coming into the browser holding information about nodes, volumes, and other resources seem to be missing the self link property.

Currently further investigating the issue.

**Comment by LLParse** [comment]
@TehTotalPwnage It seems like go-rancher isn't constructing a proper apiContext: https://github.com/rancher/longhorn-manager/blob/master/api/stream.go#L57

This is probably due to the initial HTTP ws upgrade request having a different path than what was expected. For example, `GET /v1/volumes` would instead be `GET /v1/ws/volumes` or `GET /v1/ws/2s500ms/volumes`. We could probably adjust the `http.Request` in some way right before creating the apiContext to yield proper links for the REST API.

**Comment by yasker** [comment]
@LLParse @TehTotalPwnage The link self is propagated by `apiContext.Write` e.g. https://github.com/rancher/longhorn-manager/blob/master/api/volume.go#L96

Code for propagation at https://github.com/rancher/longhorn-manager/blob/master/vendor/github.com/rancher/go-rancher/api/writer.go#L32:22

OK, looking at the code, seems we don't go through `apiContext.Write` to write the data through the websocket.

https://github.com/rancher/longhorn-manager/blob/a1683e1ed26514482b6a36457d22300353c9efa8/api/stream.go#L96

**Comment by LLParse** [comment]
@yasker You're right.

We can't call the method that adds the self link because it is private https://github.com/rancher/longhorn-manager/blob/master/vendor/github.com/rancher/go-rancher/api/writer.go#L123

We could implement our own ApiResponseWriter interface https://github.com/rancher/longhorn-manager/blob/a1683e1ed26514482b6a36457d22300353c9efa8/vendor/github.com/rancher/go-rancher/api/writer.go#L12-L14 but unfortunately there's no way to construct an `ApiContext` to use it because the field is private https://github.com/rancher/longhorn-manager/blob/master/vendor/github.com/rancher/go-rancher/api/context.go#L20

I think we have to replicate the self link logic in Longhorn codebase or release a more extensible version of the go-rancher dependency.

**Comment by yasker** [comment]
Fixed by update go-rancher to support populating the links for collection.
