### ISSUE TITLE
The file is emptied under the mount path when revert the snapshot.

### ISSUE THREAD

**Issue by rootwuj** [rancher/longhorn#232]
**Environment:**

Using rke to deploy kubernetes v1.11.1
Longhorn version: v0.3-rc4

**Steps to Reproduce:**
1. Confirm that there is already written content under the mount path. 

```
root@ip-172-31-13-154:~# kubectl exec -it volume-nginx sh
/# cd data/
/data # ls
/lost+found  test.yaml
/data #
```

2. Create a snapshot.
2. Revert the snapshot.

**Results:**
The file is emptied under the mount path.

```
 root@ip-172-31-13-154:~# kubectl exec -it volume-nginx sh
 / # cd data/
 /data # ls
 /data #
```

**Comment by yasker** [comment]
Have you unmounted the volume before performing revert? Snapshot revert is a block layer operator, if you didn't unmount the volume before the operation, the file system layer of the OS would be confused and caused error (see `dmesg` on the node). That's why we have warnings in the UI before reverting.

The unmounting would have another effect, that would sync up the cache in the file system layer to the block layer, which really `write the data` to the disk. You can do `sync` manually for this as well.

**Comment by rootwuj** [comment]
I create a pod with deployment, rebuild the pod after revert the snapshot. The restored content is correct.
