### ISSUE TITLE
Move replica to a different server

### ISSUE THREAD

**Issue by KuroObi** [rancher/longhorn#292]
Is there a way to move a replica of a volume from one server to another. Form maintenance or other reasons?

**Comment by yasker** [comment]
Not `move`, but you can achieve the same effort by forcing a rebuild.

1. Disable the scheduling for that node
2. Make sure volume is current healthy (since we're going to destroy a replica)
3. Delete the replica on the node you want for maintenance.

If any other node can be scheduled with that replica, the replica would be schedule there and started rebuilding process using the existing healthy replica. Otherwise the volume will report `unable to schedule` but still functional.

**Comment by KuroObi** [comment]
That sounds risky. Destroying the last replica of a volume.

Is this a feat feature on the roadmap?

**Comment by yasker** [comment]
The rebuilding process is essentially asking the controller to copy the data from one replica to another. The controller knows how to handle that. It's one of the basic features of the Longhorn system.

Of course, you won't want to destroy the last replica. That's why we recommended having at least 3 replicas for your volume.

Manually moving the replica won't be a feature, since we don't expect the user to be involved in this level of control. What we can do, is adding a feature to support `maintenance mode` of a node. The scheduling of the node would be disabled, and the replicas on that node would be automatically rebuilt on other nodes. After the rebuilt was done, the replicas on the original node would be destroyed. We can temporarily increase the replica number of the volume, to ensure the minimal availability user specified is still valid.

**Comment by KuroObi** [comment]
`maintenance mode` sounds like a realy good idea.

**Comment by yasker** [comment]
#298 filed. Close this one.
