### ISSUE TITLE
Mount command failed, status: Failure, The volume is existed and is attached

### ISSUE THREAD

**Issue by SacDin** [rancher/longhorn#30]
While upgrading / rolling update on the deployment, the system tries to create new pod, attach and then shutdown old pods. In this process, new replica sets are unable to attach to volume because old ones are already attached.

Error : 
```
MountVolume.SetUp failed for volume "myservice-db" : mount command failed, status: Failure, reason: myservice-db is existed and is attached
```

**Comment by yasker** [comment]
It sounds like a problem with Kubernetes rolling update and persistent volumes which only supports Access Mode `ReadWriteOnce` (which is basically all the block storage solutions, including EBS, Google Persistent Disk, AzureDisk, see [here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes))

In its current form, it cannot update pods with attached volume. According to rolling update [design doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cli/simple-rolling-update.md), Kubernetes will start the new pod first, then stop the old pod. Since the volume attached to the pod is `RWO`, it cannot be attached again to the new pod before it was detached from the old one first.

A similar issue was filed with Azure at https://github.com/kubernetes/kubernetes/issues/52236 , with a recommendation to use `AzureFile` instead of `AzureDisk`.

**Comment by SacDin** [comment]
So, there is no solution as of now ?

**Comment by yasker** [comment]
I just realize you can use `statefulset` instead of `deployment`, which is aware of the different PVCs associated with the pods. And it will do the right thing - stop the old one, then start the new one with the same volume.
