### ISSUE TITLE
File corrupted after volume revert from NFS backup

### ISSUE THREAD

**Issue by AmreeshTyagi** [rancher/longhorn#325]
I tried experimental helm chart of longhorn. Very impressive tool to manage all volumes of kubernetes cluster. But found one issue. Following are the steps, I took:

I installed minio in kubernetes with default longhorn storage class. Then, uploaded one file in minio bucket. Took backup & snapshot. Uploaded 2nd file & took backup & snapshot. I reverted backup after first file upload. 

Files disappears from minio. It seems like PV is not re-mounted. So I redeployed minio & uploaded file is appeared in minio. Then reverted backup taken after 2nd file upload. Redeployed minio, and observed that one file is in good condition, but second file was of 0 bytes & when opened this 2nd word file, text was missing.

This process corrupted my file uploaded in minio bucket.

Any idea, why volume is corrupted during revert process?

**Comment by yasker** [comment]
Are you using `revert snapshot`?

As you can see there is a warning in the `revert snapshot` operation, that it cannot be done when the volume is mounting on the node, otherwise, it will cause filesystem corruption. Because you cannot change the underlying block device without the filesystem's awareness.

Another issue is, you need to make sure the data has been written into the block device before taking snapshot. The data can be cached in the filesystem level for a period of time. Normally you can ensure the data was written using `sync` or umount the volume from the filesystem.

**Comment by AmreeshTyagi** [comment]
Thanks for quick response @yasker . Yes, I did it using `revert` option provided in snapshot drop-down menu. 

If that's is not the correct way, then what is the use of this option? 
I cann't unmount volume as it is bounded by pod's volume claim. Should I have to take some other steps before reverting or any other seamless option? 

Actually, I want to use Longhorn for MySQL HA cluster with NFS backup support.
I would be happy, if you can give your recommendation for my scenario. Little bit outside of this issue.

1. Longhorn with NFS backup or 
2. Direct NFS with seperate directories for all MySQL HA nodes or 
3. MySQL setup on native host outside Kubernetes  cluster.

**Comment by yasker** [comment]
@AmreeshTyagi Longhorn is a block storage solution like EBS. You cannot suddenly change a block device's content while the filesystem is still mounted. It's like writing to the block device directly, bypassing the filesystem, while you're still using it as a filesystem.

The `revert` can be done if you've unmounted volume but keep it attached to the node. It's not intuitive for Kubernetes since Kubernetes always want to attach and mount happens together. But for the block storage, attach and mount are two different operations.

To use the revert, you can:
1. Stop the pod.
2. Attach the volume to any node using UI. Revert to a previous snapshot. Detach the volume.
3. Start the pod again.

And make sure data are synced (e.g. by running `sync` in your container) to the block device before you took the snapshot.

For how to use backup, see my demo at https://www.youtube.com/watch?v=vRqvz-Ii49A&t=3326s

For your question on MySQL cluster, you can use Longhorn directly with backup. Block device provides better performance than NFS, and MySQL Cluster is a shared-nothing architecture which suites block storage solution better.

**Comment by AmreeshTyagi** [comment]
@yasker Thanks a lot! 
I watched the video. It's really helpful to understand the features of longhorn. It solved my problem of backup too.

I will go with your suggestion & use Longhorn with backup for MySQL HA cluster. 

Closing this issue.
