### ISSUE TITLE
If controller process is killed, replica may get destroyed and recreated

### ISSUE THREAD

**Issue by cjellick** [rancher/longhorn#35]
@sangeethah observed this as part of this bug:
https://github.com/rancher/longhorn/issues/32
but that bug's primary focus is the fact that after controller crash, file system goes to read only.

So, I'm opening this issue to track separately

Problem:
If you kill -9 the controller process, the controller will get restarted. When it does, the existing replicas won't be in the controller. Depending on how the controller takes to come back up, this can cause the replicas to go to an unhealthy state and ultimately be destroyed and recreated.

Expected:
Replica should not get deleted because it was unhealthy. It should just stay healthy and be re-added to the controller

Actual:
Under certain timing conditions, the replica goes to unhealthy and gets destroyed/recreated.

**Comment by sangeethah** [comment]
Tested with Rancher server - latest Build from master 
Ros version - v0.4.4 
Longhorn catalog template from - https://github.com/cjellick/longhorn-catalog (image - cjellick/longhorn:dev4)

Create a service(health check enabled) with VM having ROOT Volumes in longhorn. 
Once the VM has started successfully , create few files in ROOT volume.

Kill controller process.
After this controller gets restarted and gets to "healthy" state and remains in "healthy" state.
Replica containers does not get recreated (because of replica container getting to unhealthy state) in this process and remain in "healthy" state.
