### ISSUE TITLE
Suddenly our node name changed

### ISSUE THREAD

**Issue by Akhail** [rancher/longhorn#391]
We need your help because our provider Digital Ocean recycled all the instances like a consequence of a detected vulnerability in Docker. For this reaseon longhorn is not finding the volumes and replicas. How can we resolve this issue? 

Thanks!

![deepinscreenshot_select-area_20190213094204](https://user-images.githubusercontent.com/22435967/52716365-fdaa0280-2f74-11e9-98c7-5cf9bf11f15c.png)

**Comment by yasker** [comment]
@Akhail Is it a name change? From what I see here, I suspect Digital Ocean delete the instance then recreated it from scratch... That's maybe why the instance names are not the same.

Looking at the latest reported `Used`. The old node has used `26.58G` of 157G, the new node only used `8.78G`. Sorry to tell you that, but it looks like all the volumes have been deleted along with the old instance... Have you made backups for your volumes?

**Comment by Akhail** [comment]
Hey, thanks for the response!
Would't it be that the occupied space is due to the replicas? We don't have that much data.
Is there any way, through the file system, that we can access the place where the volumes were mounted and therefore access the data?

**Comment by yasker** [comment]
Yeah, the occupied space in your old instance is likely due to the storage of Longhorn replicas (a.k.a data). But as you can see, in your new instance, the `used` space is much lower (by 18G in fact), which indicates that it's a new instance, instead of a renamed instance.

So it's likely all the data in the old instance is gone with the deletion of the old instance. Any data you have written to that instance would be gone. Not only Longhorn data, but any data stored in that instance. That's the major reason we suggest you make backups outside of the cluster, to prevent this kind of failure from happening.

If you still have the old instance, we can try to get the data back.

**Comment by Akhail** [comment]
In what folder would it be, in case we could access the old instance?

**Comment by yasker** [comment]
@Akhail Take a look at the host path for each replica, the volume data is stored there.

**Comment by Akhail** [comment]
Thank you very much for your help, but it didn't work for me, all of the data are lost :/

**Comment by yasker** [comment]
@Akhail sorry to hear that... Is it a Digital Ocean Kubernetes cluster? Delete a node instance without properly notify the user is really bad practice.

**Comment by Akhail** [comment]
> @Akhail sorry to hear that... Is it a Digital Ocean Kubernetes cluster? Delete a node instance without properly notify the user is really bad practice.

Yes, it's the kubernetes service provided by digitalocean, but they did not help us at all.
