### ISSUE TITLE
Longhorn Helm Chart (usable with helm cli)

### ISSUE THREAD

**Issue by PhilippHeuer** [rancher/longhorn#445]
Right now longhorn has a helm chart which can be installed using the catalog (gui).

It would be nice to get a official helm chart, which can be used with the normal `helm` cli tool. 
I want to use this for a reproducable cluster deployment (with rke / rancher / longhorn).

Maybe that could be published in a repo like `https://releases.rancher.com/longhorn-charts/stable` same as rancher 2 has its own chart repo `https://releases.rancher.com/server-charts/stable`.

**Comment by yasker** [comment]
@PhilippHeuer I was thinking about this, now I am curious why you prefer Helm? Longhorn currently can be installed/upgraded by a single line of kubectl, uninstalled by two lines of kubectl. It doesn't like other applications that needs many configurations since we spent quite some efforts on detecting the user environment and configure Longhorn automatically.

Could you share your ideas on why you prefer Helm for Longhorn?

**Comment by PhilippHeuer** [comment]
You do already supported helm over the rancher catalog, just not as vanilla helm chart because of the different directory structure.

The reason is pretty simple, i know how to install any app with helm since it's always the same command with a different chart. But everytime i need to use kubectl apply i need to check the docs for my current version on what to do (multiple commands for setup / delete job / ..).

For example the first 2 times i uninstalled longhorn i left my cluster in a broken state since i didn't know about the uninstall job - which needed to run first. Helm takes care of such things too using hooks.

It's basically just quality-of-life - it's the same commands for every kind of service i deploy and it takes care of everything for me. At least thats the reason for me personally ;)

**Comment by yasker** [comment]
@PhilippHeuer Thanks for elaborating.

Yeah, we will include an official Helm chart in the Longhorn (besides the one using by Rancher) in the next release.
