### ISSUE TITLE
test: validate Google Cloud Storage for Longhorn backupstore

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#450]

**Comment by jaredkipe** [comment]
I have a secret named `google-cloud-storage` with a key in the secret (when viewed in the API) as 

```
AWS_ENDPOINTS: "aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29t"
```

Which base64 decodes to `https://storage.googleapis.com`.
I believe this is correct only because of this particular page. **_Google Cloud Console -> Storage -> Settings -> Interoperability (tab)_**

Here is a screenshot of the section in question.


<img width="463" alt="interop" src="https://user-images.githubusercontent.com/744550/55043245-927f3180-4ff2-11e9-9cfd-27d9777e87f3.png">

From here, I chose a 'bucket/path' s3:// url to be `s3://some-bucket-name/backupstore` I chose this path because of an error message I received from longhorn.

```
error listing backups: error listing backup volumes: 
Failed to execute: /var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.3.0/longhorn [backup ls --volume-only s3://some-bucket-name], 
output time="2019-03-27T00:39:10Z" 
level=error msg="Invalid URL. Must be either s3://bucket@region/path/, or s3://bucket/path" Invalid URL. Must be either s3://bucket@region/path/, or s3://bucket/path , error exit status 1
```

After changing that I get the following error when attempting a backup (similar when listing backups).

```
fail to backup snapshot: Failed to execute: /var/lib/rancher/longhorn/engine-binaries/rancher-longhorn-engine-v0.3.0/longhorn 
[--url http://10.42.0.66:9501 backup create --dest s3://some-backup-name/backupstore fbc93f3e-921b-4fb4-ae97-b6a14dc4016e], 
output time="2019-03-27T00:55:25Z" 
level=info 
msg="Backing up fbc93f3e-921b-4fb4-ae97-b6a14dc4016e on tcp://10.42.2.227:9502, to s3://some-bucket-name/backupstore" 
time="2019-03-27T00:55:26Z" 
level=error msg="Failed backing up fbc93f3e-921b-4fb4-ae97-b6a14dc4016e on tcp://10.42.2.227:9502 to s3://some-bucket-name/backupstore" 
time="2019-03-27T00:55:26Z" 
level=fatal msg="Error running create backup command: ExitCode: 1, output: AWS Error: MissingRegion could not find region configuration <nil>\n\n" , error exit status 1
```

**Comment by jaredkipe** [comment]
@yasker Pointed out the documentation ( https://cloud.google.com/storage/docs/locations ) that suggested my above s3:// uri should have been `s3://some-bucket-name@us/backupstore` 

This does indeed create backups, though with a double indenting, which isn't really a problem, but included for completeness.

<img width="790" alt="Backup-success-duplicate-folder" src="https://user-images.githubusercontent.com/744550/55043856-41bd0800-4ff5-11e9-8fb7-4315697851dc.png">

**Comment by yasker** [comment]
Seems we've validated this. Thanks to @jaredkipe !

I've also updated the doc to emphasis the region code.
