### ISSUE TITLE
After snapshot revert  Input/output error

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/longhorn#7]
Hi 

I created a single box setup and created volume with a 2 replica with 20GB after that
I followed these steps.

mkfs.xfs /dev/longhorn/test
mount /dev/longhorn/test /mnt
cd /mnt
touch test1 test2

On UI I took the snapshot after that I took snapshot 
rm test1
Again back to UI and I click the snapshot are revert
cd /mnt 
ls
ls: cannot open directory '.': Input/output error

**Comment by sjkeerthi** [comment]
After I umount and mounted the file I don't see any files which I touched

**Comment by yasker** [comment]
@sjkeerthi In fact revert shouldn't be allowed when fs is mounted.

It's a normal block device. If you don't run `sync` or `umount`, the file may not be written to the block device. That's why you didn't see it.

And you got IO error because the block device changed and the old mount expired.

Try again follow steps:
1. Create the block device.
2. Format, mount
3. Write file to it. Probably run `sync` as well. Then take a snapshot.
4. Make more changes. 
5. Unmount the block device.
6. Revert to the early snapshot. You should see the change.

**Comment by yasker** [comment]
Close this for now. Please reopen if it doesn't work as expected.
